name: "Run unit tests"
description: "Make sure all tests pass"

inputs:
  node-version:
    description: "The version of Node to run the tests against"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    # Install Node
    - name: Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "npm"
    - name: Confirm installed Node version
      run: node -v

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm run test
